# Generated by Django 2.2.6 on 2020-04-09 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0004_profile_reserved'),
        ('daycalendar', '0010_setting_transfer'),
        ('management', '0003_moneyoperations_orders_typeofmo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacantedShifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('M', 'Утренняя'), ('R', 'Резервная'), ('E', 'Вечерняя')], default='Утренняя', max_length=10, verbose_name='Смена')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='daycalendar.Day', verbose_name='День')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enter.Profile', verbose_name='Администратор')),
            ],
            options={
                'verbose_name_plural': 'Вакантные смены',
                'verbose_name': 'Вакантные смены',
            },
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('M', 'Утренняя'), ('E', 'Вечерняя')], default='Утренняя', max_length=10, verbose_name='Смена')),
                ('pref', models.CharField(blank=True, choices=[('+', 'Предпочтительно'), ('=', 'Все равно'), ('-', 'Нежелательно')], default='Все равно', max_length=20, null=True, verbose_name='Выбор')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='daycalendar.Day', verbose_name='День')),
            ],
            options={
                'verbose_name_plural': 'Предпочтения',
                'verbose_name': 'Предпочтения',
            },
        ),
        migrations.CreateModel(
            name='FuturePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('M', 'Утренняя'), ('R', 'Резервная'), ('E', 'Вечерняя')], default='Утренняя', max_length=18, verbose_name='Смена')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='daycalendar.Day', verbose_name='День')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enter.Profile', verbose_name='Администратор')),
            ],
            options={
                'verbose_name_plural': 'План смен на следующую неделю',
                'verbose_name': 'План смен на следующую неделю',
            },
        ),
        migrations.CreateModel(
            name='CurrentPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('M', 'Утренняя'), ('R', 'Резервная'), ('E', 'Вечерняя')], default='Утренняя', max_length=18, verbose_name='Смена')),
                ('eveningActivity', models.BooleanField(default=False, verbose_name='Резервная смена активна')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='daycalendar.Day', verbose_name='День')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enter.Profile', verbose_name='Администратор')),
            ],
            options={
                'verbose_name_plural': 'Текущий план смен',
                'verbose_name': 'Текущий план смен',
            },
        ),
    ]
