# Generated by Django 2.2.6 on 2020-04-09 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0004_profile_reserved'),
        ('management', '0004_currentplan_futureplan_preferences_vacantedshifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enter.Profile', verbose_name='Администратор'),
        ),
    ]
