# Generated by Django 2.2.6 on 2020-04-14 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20200414_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='preferences', to='enter.Profile', verbose_name='Администратор'),
        ),
    ]
