# Generated by Django 2.2.6 on 2020-02-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Телефон клиента'),
        ),
    ]
