# Generated by Django 2.2.6 on 2020-02-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200207_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='includes',
            field=models.ManyToManyField(blank=True, help_text='Выбранные бесплатные услуги', to='main.IncludeService', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='booking',
            name='services',
            field=models.ManyToManyField(blank=True, to='main.AddService', verbose_name='Выбранные платные услуги'),
        ),
    ]
