# Generated by Django 2.2.6 on 2020-02-19 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20200215_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата брони'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Выбранные платные услуги', to='main.AddService', verbose_name=''),
        ),
    ]
