# Generated by Django 2.2.6 on 2020-02-20 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200108_2257'),
        ('booking', '0006_auto_20200220_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Discount', verbose_name='Скидка'),
        ),
    ]
