# Generated by Django 2.2.6 on 2019-12-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191228_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='owner',
            field=models.BooleanField(default=False, verbose_name='Особые права при оплате'),
        ),
    ]
