# Generated by Django 2.2.6 on 2020-01-02 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_session_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='card',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.CardPay', verbose_name='Безнал'),
        ),
        migrations.AlterField(
            model_name='session',
            name='cash',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.CashPay', verbose_name='Наличные'),
        ),
        migrations.AlterField(
            model_name='session',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='session',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Room', verbose_name='Занятая комната'),
        ),
    ]
