# Generated by Django 2.2.6 on 2020-01-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_company_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='SID',
            field=models.CharField(max_length=100, verbose_name='SID'),
        ),
    ]
