# Generated by Django 2.2.6 on 2020-02-21 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200108_2257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['id'], 'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
    ]
