# Generated by Django 2.2.6 on 2020-04-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200221_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpay',
            name='is_usersalary',
            field=models.BooleanField(default=False, verbose_name='Учтено в зарпалатном начислении'),
        ),
        migrations.AddField(
            model_name='cashpay',
            name='is_usersalary',
            field=models.BooleanField(default=False, verbose_name='Учтено в зарпалатном начислении'),
        ),
    ]
