# Generated by Django 2.2.6 on 2019-12-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Дни недели',
                'verbose_name': 'Дни недели',
            },
        ),
    ]
