# Generated by Django 2.2.6 on 2020-01-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycalendar', '0003_setting_delete_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='num',
            field=models.IntegerField(default=0, verbose_name='Порядковый номер'),
        ),
    ]
