# Generated by Django 2.2.6 on 2020-02-19 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycalendar', '0005_auto_20200109_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='start',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Обычное время начала смены'),
            preserve_default=False,
        ),
    ]
