# Generated by Django 2.2.6 on 2020-03-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycalendar', '0008_setting_weekend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='end',
            field=models.TimeField(default=None, null=True, verbose_name='Обычное время конца смены'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='weekend',
            field=models.TimeField(default=None, null=True, verbose_name='Предпраздничное время конца смены'),
        ),
    ]
