# Generated by Django 2.2.6 on 2020-03-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycalendar', '0009_auto_20200318_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='transfer',
            field=models.TimeField(default=None, null=True, verbose_name='Обычное время пересмены'),
        ),
    ]
