# Generated by Django 2.2.6 on 2020-04-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycalendar', '0010_setting_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='is_build',
            field=models.BooleanField(default=False, verbose_name='График построен'),
        ),
    ]
