# Generated by Django 2.2.6 on 2019-10-30 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enter.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseRate', models.PositiveSmallIntegerField(verbose_name='Базовая ставка')),
                ('bonusRate', models.PositiveSmallIntegerField(verbose_name='Бонусная ставка')),
                ('procent', models.SmallIntegerField(default=2, verbose_name='Процент от выручки')),
                ('enter', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время входа')),
                ('countG', models.IntegerField(default=0, verbose_name='Счётчик предпочтительных смен')),
                ('countB', models.IntegerField(default=0, verbose_name='Счётчик нежелательных смен')),
                ('restB', models.IntegerField(default=0, verbose_name='Осталось нежелательных смен')),
                ('color', enter.fields.ColorField(default='#FF0000', max_length=7, verbose_name='Цвет обложки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Администраторы',
                'verbose_name': 'Администратор ',
            },
        ),
    ]
