# Generated by Django 2.2.6 on 2019-10-30 18:02

from django.db import migrations
import enter.fields


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='color',
            field=enter.fields.ColorField(default='#FF0000', max_length=7, verbose_name='Цвет админа'),
        ),
    ]
