# Generated by Django 2.2.6 on 2019-10-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0002_auto_20191030_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='baseRate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bonusRate',
        ),
        migrations.AddField(
            model_name='profile',
            name='base',
            field=models.PositiveSmallIntegerField(default=45, verbose_name='Базовая ставка'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bonus',
            field=models.PositiveSmallIntegerField(default=25, verbose_name='Бонусная ставка'),
        ),
    ]
