# Generated by Django 2.2.6 on 2019-12-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enter', '0003_auto_20191030_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reserved',
            field=models.BooleanField(default=False, verbose_name='Работает в резерв'),
        ),
    ]
